Repository opiproject/opi-api, pull requests merged in 2022-07, with the labels that each got.

#35 Add API GW and Vendor Layers
  doc/minutes/images/API-GW-Layers.png
Labels: documentation

#50 CI: Add golang proto generation
  .github/workflows/storage-skip.yml
  .github/workflows/storage.yml
  README.md
  storage/Makefile
Labels: CI

#60 Fix broken link
  security/README.md
Labels: bug
